# Generated by Django 5.0 on 2023-12-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('price', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=20)),
            ],
        ),
    ]
